### ISSUE TITLE
Error loading 'CommandListener' listener! Listener disabled.

### ISSUE THREAD

**Issue by uncovery** [CoolV1994/CommandListener#1]
I am getting the error:

 Error loading 'CommandListener' listener! Listener disabled.

When trying to use this listener. Any Idea what is wrong? 
Using Votifier 1.9 and Spigot 1.8.8

**Comment by CoolV1994** [comment]
The Command Listener should work fine on Spigot 1.8.8.
What version of Java are you using?
Also is there any other errors in your server.log file?

**Comment by uncovery** [comment]
Thanks for the quick reply. No other errors. 
java version "1.7.0_91"

**Comment by CoolV1994** [comment]
I believe this was compiled with Java 8.
I will compile a Java 7 compatible version.

**Comment by uncovery** [comment]
That would be great, thanks!

**Comment by CoolV1994** [comment]
I have uploaded version 1.2.
https://github.com/CoolV1994/CommandListener/releases/tag/1.2-bukkit

Please let me know if this version works.

**Comment by uncovery** [comment]
yes, that worked! thanks!
